# Generated by Django 4.2.7 on 2025-08-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secuencias", "0002_alter_secuencias_sistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="secuencias",
            name="fecha_registro",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Registro"
            ),
        ),
        migrations.AddField(
            model_name="secuencias",
            name="registrada_por",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Registrada por"
            ),
        ),
    ]
