# Generated by Django 4.2.7 on 2025-08-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Protocolo_Metodos",
            "0002_protocolos_entregado_a_protocolos_fecha_de_entrega",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolos",
            name="fecha_de_entrega",
            field=models.DateField(
                blank=True,
                help_text="AAAA/MM/DD",
                null=True,
                verbose_name="Fecha de Entrega",
            ),
        ),
    ]
